name: Actualizar Token
on:
  schedule:
    - cron: '*/30 * * * *' # Se ejecuta cada 30 minutos
  workflow_dispatch:      # Bot√≥n para ejecutarlo a mano
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Ejecutar Script
        run: |
          pip install requests
          python get_token.py
      - name: Guardar Cambios
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add enlace.txt
          git commit -m "Update" || echo "No changes"
          git push
